apiVersion: v1
kind: Service
metadata:
  name: svc-auth
  namespace: planara
spec:
  type: ClusterIP
  selector:
    app: svc-auth
  ports:
    - name: http
      port: 8080
      targetPort: 8080

    - name: management
      port: 8081
      targetPort: 8081