name: publish-k3s

on:
  workflow_dispatch:

concurrency:
  group: svc-auth-prod
  cancel-in-progress: false

jobs:
  publish-auth-api:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set deploy variables
        id: vars
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          SHA="$(git rev-parse HEAD)"

          echo "image=ghcr.io/${OWNER_LC}/planara-auth" >> $GITHUB_OUTPUT
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check image exists
        run: |
          docker buildx imagetools inspect ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.sha }}

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/planara_vps
          chmod 600 ~/.ssh/planara_vps
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Upload manifests
        run: |
          ssh -i ~/.ssh/planara_vps ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "mkdir -p ~/planara-deploy/svc-auth/k8s/prod"

          scp -i ~/.ssh/planara_vps -r k8s/prod/* \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/planara-deploy/svc-auth/k8s/prod/

      - name: Apply manifests
        run: |
          ssh -i ~/.ssh/planara_vps ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "sudo k3s kubectl apply -f ~/planara-deploy/svc-auth/k8s/prod"

      - name: Set image
        run: |
          ssh -i ~/.ssh/planara_vps ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "sudo k3s kubectl -n planara set image deployment/svc-auth svc-auth=${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.sha }}"

      - name: Wait rollout
        run: |
          ssh -i ~/.ssh/planara_vps ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "sudo k3s kubectl -n planara rollout status deployment/svc-auth --timeout=180s"

      - name: Show status
        run: |
          ssh -i ~/.ssh/planara_vps ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "sudo k3s kubectl -n planara get pods && sudo k3s kubectl -n planara get svc svc-auth"